import type { ReportSection } from '@/types';

interface ReportDocumentProps {
  reportNo: string;
  date: string;
  analyst?: string;
  sections: ReportSection[];
}

function SectionBody({ section }: { section: ReportSection }) {
  if (section.rows) {
    return (
      <table className="w-full text-sm">
        <tbody>
          {section.rows.map((row) => (
            <tr key={row.label} className="border-b border-gray-100">
              <td className="w-1/3 py-2 pr-4 font-medium text-gray-600">{row.label}</td>
              <td className="py-2 tabular-nums text-gray-900">{row.value}</td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  }

  if (section.table) {
    return (
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b border-gray-300 bg-gray-50 text-left text-xs font-semibold uppercase tracking-wide text-gray-600">
            {section.table.headers.map((h) => (
              <th key={h} className="px-3 py-2">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {section.table.rows.map((row, i) => (
            <tr key={i} className="border-b border-gray-100 last:border-b-0">
              {row.map((cell, j) => (
                <td key={j} className="px-3 py-2 text-gray-900">
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    );
  }

  if (section.list) {
    return (
      <ol className="space-y-1.5 text-sm text-gray-700">
        {section.list.map((item, i) => (
          <li key={i} className="flex gap-2">
            <span className="select-none font-medium text-gray-400">{i + 1}.</span>
            {item}
          </li>
        ))}
      </ol>
    );
  }

  return <p className="text-sm text-gray-600">{section.emptyMessage}</p>;
}

export function ReportDocument({ reportNo, date, analyst = 'Laboratory Staff', sections }: ReportDocumentProps) {
  return (
    <article className="print-area border border-gray-300 bg-white">
      <header className="border-b-2 border-gray-800 px-8 py-6">
        <div className="flex items-start justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-gray-500">
              Dissolved Gas Analysis Report
            </p>
            <h2 className="mt-1 text-xl font-bold text-gray-900">
              DTL DGA Analysis System
            </h2>
            <p className="mt-1 text-sm text-gray-600">Power Utility Laboratory</p>
          </div>
          <div className="text-right text-sm">
            <p>
              <span className="font-medium text-gray-700">Report No:</span> {reportNo}
            </p>
            <p>
              <span className="font-medium text-gray-700">Date:</span> {date}
            </p>
            <p>
              <span className="font-medium text-gray-700">Analyst:</span> {analyst}
            </p>
          </div>
        </div>
      </header>

      <div className="px-8 py-6">
        {sections.map((section) => (
          <section key={section.title} className="mb-8 last:mb-0">
            <h3 className="mb-3 border-b border-gray-300 pb-1 text-sm font-bold uppercase tracking-wide text-gray-800">
              {section.title}
            </h3>
            {section.note && <p className="mb-2 text-xs text-gray-500">{section.note}</p>}
            <SectionBody section={section} />
            {section.footnote && (
              <p className="mt-3 text-xs italic text-gray-500">{section.footnote}</p>
            )}
          </section>
        ))}
      </div>

      <footer className="border-t border-gray-300 px-8 py-4">
        <div className="flex justify-between text-xs text-gray-500">
          <p>Generated by DTL DGA Analysis System — IEEE C57.104-2019</p>
          <p>Page 1 of 1</p>
        </div>
      </footer>
    </article>
  );
}
